title: TPEN
logo: /assets/img/logo.png
baseurl: /
description: Transcription powered by Rerum.
show_downloads: false
google_analytics: G-630J3K9FNK
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
